language: objective-c
osx_image: xcode8.3
sudo: false
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - pod install --repo-update
script:
  - set -o pipefail
  - xcodebuild test -workspace MotionInterchange.xcworkspace -scheme MotionInterchangeCatalog -sdk "iphonesimulator10.3" -destination "name=iPhone SE,OS=10.3" -enableCodeCoverage YES ONLY_ACTIVE_ARCH=YES | xcpretty -c;
after_success:
  - bash <(curl -s https://codecov.io/bash)
